### ISSUE TITLE
Duas verificações iguais no mesmo if

### ISSUE THREAD

**Issue by Valdjr** [EstevaoAnderle/Projeto_Warcraft#2]
https://github.com/EstevaoAnderle/Projeto_Warcraft/blob/01557175a5b9965c13592e61ca3c1ea854b1e668/src/projetowarcraft/objetos/Custo.java#L71

Nessa ultima verificação do IF acredito que deve ser algo como: this.mana >= custo.getMana().

**Comment by EstevaoAnderle** [comment]
Era exatamente isso! Corrigido já :D
